<?php

function cmsModuleConfig(string $module): array
{
    $commonStatus = cmsStatusOptions();

    $configs = [
        'brands' => [
            'title' => 'Brands',
            'singular' => 'Brand',
            'description' => 'Manage represented brands and manufacturer information.',
            'path' => '/admin/brands.php',
            'table' => 'brands',
            'sessionKey' => 'brands',
            'slugSource' => 'name',
            'created_by' => true,
            'updated_by' => true,
            'required' => ['name', 'slug', 'status'],
            'statusFieldValues' => ['status' => array_keys($commonStatus)],
            'labels' => [
                'name' => 'Brand Name',
                'slug' => 'Slug',
                'logo_path' => 'Logo Path',
                'overview' => 'Overview',
                'is_featured' => 'Featured',
                'status' => 'Status',
                'display_order' => 'Display Order',
            ],
            'fields' => [
                'name' => ['type' => 'text'],
                'slug' => ['type' => 'text'],
                'logo_path' => ['type' => 'text'],
                'overview' => ['type' => 'textarea'],
                'is_featured' => ['type' => 'checkbox'],
                'status' => ['type' => 'select', 'options' => $commonStatus, 'default' => 'active'],
                'display_order' => ['type' => 'number', 'default' => 0],
            ],
            'listTitle' => 'Brand List',
            'listColumns' => ['name' => 'Name', 'slug' => 'Slug', 'status' => 'Status', 'display_order' => 'Order'],
        ],
        'product_groups' => [
            'title' => 'Product Groups',
            'singular' => 'Product Group',
            'description' => 'Group multiple products under a single expandable card on a category page (one top card, several bottom detail cards, each with its own image and final product page).',
            'path' => '/admin/product-groups.php',
            'table' => 'product_groups',
            'sessionKey' => 'product_groups',
            'slugSource' => 'name',
            'created_by' => true,
            'updated_by' => true,
            'required' => ['name', 'slug', 'status'],
            'statusFieldValues' => ['status' => array_keys($commonStatus)],
            'labels' => [
                'name' => 'Group Name',
                'slug' => 'Slug',
                'image_path' => 'Image Path',
                'description' => 'Description',
                'status' => 'Status',
                'display_order' => 'Display Order',
            ],
            'fields' => [
                'name' => ['type' => 'text'],
                'slug' => ['type' => 'text'],
                'image_path' => ['type' => 'text', 'hint' => 'Shown on the top-level card that represents this whole group, e.g. images/foldername/filename.jpg'],
                'description' => ['type' => 'textarea'],
                'status' => ['type' => 'select', 'options' => $commonStatus, 'default' => 'active'],
                'display_order' => ['type' => 'number', 'default' => 0],
            ],
            'listTitle' => 'Product Group List',
            'listColumns' => ['name' => 'Name', 'slug' => 'Slug', 'status' => 'Status', 'display_order' => 'Order'],
        ],
        'products' => [
            'title' => 'Products',
            'singular' => 'Product',
            'description' => 'Manage product catalog records and publishing status.',
            'path' => '/admin/products.php',
            'table' => 'products',
            'sessionKey' => 'products',
            'slugSource' => 'name',
            'created_by' => true,
            'updated_by' => true,
            'required' => ['category_id', 'name', 'slug', 'status'],
            'statusFieldValues' => ['status' => ['draft', 'published', 'archived']],
            'labels' => [
                'category_id' => 'Category',
                'group_id' => 'Product Group',
                'brand_id' => 'Brand',
                'name' => 'Product Name',
                'slug' => 'Slug',
                'product_line' => 'Product Line',
                'short_description' => 'Short Description',
                'image_path' => 'Image Path',
                'features' => 'Features',
                'part_numbers' => 'Part Numbers',
                'part_number_spec1_label' => 'Part Number Column 1 Heading',
                'part_number_spec2_label' => 'Part Number Column 2 Heading',
                'catalog_url' => 'Catalog URL',
                'video_url' => 'Video URL',
                'status' => 'Status',
                'is_featured' => 'Featured',
                'display_order' => 'Display Order',
            ],
            'fields' => [
                'category_id' => ['type' => 'select_int', 'options' => cmsCategoryOptions()],
                'group_id' => ['type' => 'select_int', 'options' => cmsProductGroupOptions(), 'hint' => 'Optional. Select the same Product Group on 2+ products to combine them under one top-level card on the category page — each will still show its own image and lead to its own product page when opened.'],
                'brand_id' => ['type' => 'select_int', 'options' => cmsBrandOptions()],
                'name' => ['type' => 'text'],
                'slug' => ['type' => 'text'],
                'product_line' => ['type' => 'text'],
                'short_description' => ['type' => 'textarea'],
                'image_path' => ['type' => 'text'],
                'features' => ['type' => 'longtext'],
                'part_number_spec1_label' => ['type' => 'text', 'hint' => 'Column heading for the first spec value (e.g. Bore Size). Leave blank to hide this column.'],
                'part_number_spec2_label' => ['type' => 'text', 'hint' => 'Column heading for the second spec value (e.g. Body Size). Leave blank to hide this column.'],
                'part_numbers' => ['type' => 'textarea', 'hint' => 'One per line: Part Number | Description | Column 1 value | Column 2 value (e.g. VBA10A-02GN | Booster Regulator with pressure gauge, silencer | 1/4" | 1/4"). Description and both values are optional.'],
                'catalog_url' => ['type' => 'text'],
                'video_url' => ['type' => 'text'],
                'status' => ['type' => 'select', 'options' => cmsStatusOptions(['draft', 'published', 'archived']), 'default' => 'draft'],
                'is_featured' => ['type' => 'checkbox'],
                'display_order' => ['type' => 'number', 'default' => 0],
            ],
            'listTitle' => 'Product List',
            'listColumns' => ['name' => 'Name', 'slug' => 'Slug', 'status' => 'Status', 'display_order' => 'Order'],
        ],
        'downloads' => [
            'title' => 'Downloads',
            'singular' => 'Download',
            'description' => 'Manage PDF documents for products, brands, and categories.',
            'path' => '/admin/downloads.php',
            'table' => 'product_pdfs',
            'orderBy' => 'created_at DESC, id DESC',
            'sessionKey' => 'downloads',
            'slugSource' => 'title',
            'uploaded_by' => true,
            'updated_by' => true,
            'required' => ['title', 'slug', 'document_type', 'file_path', 'status'],
            'statusFieldValues' => ['status' => ['active', 'archived']],
            'labels' => [
                'title' => 'Title',
                'slug' => 'Slug',
                'document_type' => 'Document Type',
                'file_path' => 'PDF Path',
                'file_size' => 'File Size',
                'version_label' => 'Version Label',
                'description' => 'Description',
                'product_id' => 'Product',
                'brand_id' => 'Brand',
                'category_id' => 'Category',
                'status' => 'Status',
            ],
            'fields' => [
                'title' => ['type' => 'text'],
                'slug' => ['type' => 'text'],
                'document_type' => ['type' => 'text', 'default' => 'brochure'],
                'file_path' => ['type' => 'text'],
                'file_size' => ['type' => 'number', 'default' => 0],
                'version_label' => ['type' => 'text'],
                'description' => ['type' => 'textarea'],
                'product_id' => ['type' => 'select_int', 'options' => cmsProductOptions()],
                'brand_id' => ['type' => 'select_int', 'options' => cmsBrandOptions()],
                'category_id' => ['type' => 'select_int', 'options' => cmsCategoryOptions()],
                'status' => ['type' => 'select', 'options' => cmsStatusOptions(['active', 'archived']), 'default' => 'active'],
            ],
            'listTitle' => 'Download List',
            'listColumns' => ['title' => 'Title', 'document_type' => 'Type', 'file_path' => 'File', 'status' => 'Status'],
        ],
        'product_images' => [
            'title' => 'Product Images',
            'singular' => 'Product Image',
            'description' => 'Attach image records to products.',
            'path' => '/admin/product-images.php',
            'table' => 'product_images',
            'sessionKey' => 'product_images',
            'uploaded_by' => true,
            'updated_by' => true,
            'required' => ['product_id', 'image_path', 'status'],
            'statusFieldValues' => ['status' => ['active', 'archived']],
            'labels' => [
                'product_id' => 'Product',
                'media_file_id' => 'Media File',
                'image_path' => 'Image Path',
                'title' => 'Title',
                'alt_text' => 'Alt Text',
                'caption' => 'Caption',
                'is_primary' => 'Primary Image',
                'status' => 'Status',
                'display_order' => 'Display Order',
            ],
            'fields' => [
                'product_id' => ['type' => 'select_int', 'options' => cmsProductOptions()],
                'media_file_id' => ['type' => 'select_int', 'options' => cmsMediaFileOptions(), 'hint' => 'Selecting a file here fills in Image Path automatically. Upload new files from Media first.'],
                'image_path' => ['type' => 'text', 'hint' => 'Filled in automatically when a Media File is selected above, or type a path manually (e.g. images/your-file.webp).'],
                'title' => ['type' => 'text'],
                'alt_text' => ['type' => 'text'],
                'caption' => ['type' => 'textarea'],
                'is_primary' => ['type' => 'checkbox'],
                'status' => ['type' => 'select', 'options' => cmsStatusOptions(['active', 'archived']), 'default' => 'active'],
                'display_order' => ['type' => 'number', 'default' => 0],
            ],
            'listTitle' => 'Product Image Records',
            'listColumns' => ['product_id' => 'Product ID', 'image_path' => 'Image', 'status' => 'Status', 'display_order' => 'Order'],
        ],
        'gallery' => [
            'title' => 'Gallery Albums',
            'singular' => 'Gallery Album',
            'description' => 'Manage gallery albums for public visual content.',
            'path' => '/admin/gallery.php',
            'table' => 'gallery_albums',
            'sessionKey' => 'gallery',
            'slugSource' => 'name',
            'created_by' => true,
            'updated_by' => true,
            'required' => ['name', 'slug', 'status'],
            'statusFieldValues' => ['status' => array_keys($commonStatus)],
            'labels' => [
                'name' => 'Album Name',
                'slug' => 'Slug',
                'description' => 'Description',
                'cover_image_path' => 'Cover Image Path',
                'album_type' => 'Album Type',
                'status' => 'Status',
                'display_order' => 'Display Order',
            ],
            'fields' => [
                'name' => ['type' => 'text'],
                'slug' => ['type' => 'text'],
                'description' => ['type' => 'textarea'],
                'cover_image_path' => ['type' => 'text'],
                'album_type' => ['type' => 'text', 'default' => 'general'],
                'status' => ['type' => 'select', 'options' => $commonStatus, 'default' => 'active'],
                'display_order' => ['type' => 'number', 'default' => 0],
            ],
            'listTitle' => 'Album List',
            'listColumns' => ['name' => 'Name', 'slug' => 'Slug', 'album_type' => 'Type', 'status' => 'Status'],
        ],
        'gallery_images' => [
            'title' => 'Gallery Images',
            'singular' => 'Gallery Image',
            'description' => 'Attach images to gallery albums and optional product or brand context.',
            'path' => '/admin/gallery-images.php',
            'table' => 'gallery_images',
            'sessionKey' => 'gallery_images',
            'uploaded_by' => true,
            'updated_by' => true,
            'required' => ['album_id', 'image_path', 'title', 'status'],
            'statusFieldValues' => ['status' => ['active', 'archived']],
            'labels' => [
                'album_id' => 'Album ID',
                'product_id' => 'Product',
                'brand_id' => 'Brand',
                'media_file_id' => 'Media File',
                'image_path' => 'Image Path',
                'title' => 'Title',
                'caption' => 'Caption',
                'alt_text' => 'Alt Text',
                'status' => 'Status',
                'display_order' => 'Display Order',
            ],
            'fields' => [
                'album_id' => ['type' => 'select_int', 'options' => cmsGalleryAlbumOptions()],
                'product_id' => ['type' => 'select_int', 'options' => cmsProductOptions()],
                'brand_id' => ['type' => 'select_int', 'options' => cmsBrandOptions()],
                'media_file_id' => ['type' => 'select_int', 'options' => cmsMediaFileOptions(), 'hint' => 'Selecting a file here fills in Image Path automatically. Upload new files from Media first.'],
                'image_path' => ['type' => 'text', 'hint' => 'Filled in automatically when a Media File is selected above, or type a path manually (e.g. images/your-file.webp).'],
                'title' => ['type' => 'text'],
                'caption' => ['type' => 'textarea'],
                'alt_text' => ['type' => 'text'],
                'status' => ['type' => 'select', 'options' => cmsStatusOptions(['active', 'archived']), 'default' => 'active'],
                'display_order' => ['type' => 'number', 'default' => 0],
            ],
            'listTitle' => 'Gallery Image Records',
            'listColumns' => ['album_id' => 'Album ID', 'title' => 'Title', 'image_path' => 'Image', 'status' => 'Status'],
        ],
        'seo' => [
            'title' => 'SEO Metadata',
            'singular' => 'SEO Record',
            'description' => 'Manage metadata for static and CMS-driven public pages.',
            'path' => '/admin/seo.php',
            'table' => 'seo_metadata',
            'orderBy' => 'updated_at DESC, id DESC',
            'sessionKey' => 'seo',
            'created_by' => true,
            'updated_by' => true,
            'required' => ['entity_type', 'meta_title', 'status'],
            'statusFieldValues' => ['status' => array_keys($commonStatus)],
            'labels' => [
                'entity_type' => 'Entity Type',
                'entity_id' => 'Entity ID',
                'page_path' => 'Page Path',
                'meta_title' => 'Meta Title',
                'meta_description' => 'Meta Description',
                'canonical_url' => 'Canonical URL',
                'robots' => 'Robots',
                'status' => 'Status',
            ],
            'fields' => [
                'entity_type' => ['type' => 'text', 'default' => 'page'],
                'entity_id' => ['type' => 'number'],
                'page_path' => ['type' => 'text'],
                'meta_title' => ['type' => 'text'],
                'meta_description' => ['type' => 'textarea'],
                'canonical_url' => ['type' => 'text'],
                'robots' => ['type' => 'text', 'default' => 'index, follow'],
                'status' => ['type' => 'select', 'options' => $commonStatus, 'default' => 'active'],
            ],
            'listTitle' => 'SEO Records',
            'listColumns' => ['entity_type' => 'Entity', 'page_path' => 'Path', 'meta_title' => 'Title', 'status' => 'Status'],
        ],
        'sliders' => [
            'title' => 'Sliders',
            'singular' => 'Slide',
            'description' => 'Manage homepage and promotional slider content.',
            'path' => '/admin/sliders.php',
            'table' => 'sliders',
            'sessionKey' => 'sliders',
            'created_by' => true,
            'updated_by' => true,
            'required' => ['title', 'status'],
            'statusFieldValues' => ['status' => array_keys($commonStatus)],
            'labels' => [
                'title' => 'Slide Title',
                'supporting_text' => 'Supporting Text',
                'image_path' => 'Image Path',
                'link_url' => 'Link URL',
                'button_label' => 'Button Label',
                'status' => 'Status',
                'display_order' => 'Display Order',
            ],
            'fields' => [
                'title' => ['type' => 'text'],
                'supporting_text' => ['type' => 'textarea'],
                'image_path' => ['type' => 'text'],
                'link_url' => ['type' => 'text'],
                'button_label' => ['type' => 'text'],
                'status' => ['type' => 'select', 'options' => $commonStatus, 'default' => 'active'],
                'display_order' => ['type' => 'number', 'default' => 0],
            ],
            'listTitle' => 'Slide List',
            'listColumns' => ['title' => 'Title', 'link_url' => 'Link', 'status' => 'Status', 'display_order' => 'Order'],
        ],
        'testimonials' => [
            'title' => 'Testimonials',
            'singular' => 'Testimonial',
            'description' => 'Manage public testimonials and trust content.',
            'path' => '/admin/testimonials.php',
            'table' => 'testimonials',
            'sessionKey' => 'testimonials',
            'created_by' => true,
            'updated_by' => true,
            'required' => ['display_name', 'testimonial_text', 'status'],
            'statusFieldValues' => ['status' => array_keys($commonStatus)],
            'labels' => [
                'display_name' => 'Display Name',
                'designation' => 'Designation / Company',
                'testimonial_text' => 'Testimonial Text',
                'image_path' => 'Image Path',
                'is_featured' => 'Featured',
                'status' => 'Status',
                'display_order' => 'Display Order',
            ],
            'fields' => [
                'display_name' => ['type' => 'text'],
                'designation' => ['type' => 'text'],
                'testimonial_text' => ['type' => 'textarea'],
                'image_path' => ['type' => 'text'],
                'is_featured' => ['type' => 'checkbox'],
                'status' => ['type' => 'select', 'options' => $commonStatus, 'default' => 'active'],
                'display_order' => ['type' => 'number', 'default' => 0],
            ],
            'listTitle' => 'Testimonial List',
            'listColumns' => ['display_name' => 'Name', 'designation' => 'Designation', 'status' => 'Status', 'display_order' => 'Order'],
        ],
    ];

    return $configs[$module] ?? throw new InvalidArgumentException('Unknown CMS module: ' . $module);
}

function renderCmsModuleAdmin(string $module): void
{
    $config = cmsModuleConfig($module);
    $controller = new CmsModuleController($config);

    if ($_SERVER['REQUEST_METHOD'] === 'POST') {
        $controller->handlePost();
    }

    $data = $controller->index();

    if (isset($_SESSION[$config['sessionKey'] . '_form'])) {
        $data['form'] = array_merge($data['form'], $_SESSION[$config['sessionKey'] . '_form']);
        unset($_SESSION[$config['sessionKey'] . '_form']);
    }

    if (isset($_SESSION[$config['sessionKey'] . '_errors'])) {
        $data['errors'] = $_SESSION[$config['sessionKey'] . '_errors'];
        unset($_SESSION[$config['sessionKey'] . '_errors']);
    }

    renderView('admin/cms-module', $data, 'admin');
}
